version: '2'

services:
 neo4j:
  image: neo4j:3.0.1
  ports:
   - "0.0.0.0:7474:7474"
   - "0.0.0.0:7473:7473"
   - "0.0.0.0:7687:7687"
   - "0.0.0.0:2222:22"
  environment:
   - NEO4J_AUTH=none
  networks:
   - acuo
  #volumes:
  #	- /data:/var/lib/neo4j/data
 app:
  build: ./build
  #image: localhost:5000/com.acuo.collateral/webapp:1.0
  image: webapp
  ports:
   - "0.0.0.0:8080:8080"  
  networks:
   - acuo
  #volumes:
  # - /data:/data
networks:
 acuo: