neo4j:
  image: tpires/neo4j
  ports:
    - "0.0.0.0:7474:7474"
    - "0.0.0.0:7473:7473"
    - "0.0.0.0:2222:22"
  environment:
    - NEO4J_AUTH=none
  #volumes:
  #  - /data:/var/lib/neo4j/data
app:
  build: ./webapp/build/docker
  ports:
    - "0.0.0.0:8080:8080"
  links:
    - neo4j:tpires/neo4j